### ISSUE TITLE
Use CSS instead of JS for floating docs banner

### ISSUE THREAD

**Issue by adamzap** [django/djangoproject.com#1988]
When I refactored the JavaScript for the floating docs banner in #1972, I suggested using a CSS-only solution. I tried unsuccessfully in #1799, but I hope `position: sticky` could still work somehow.

Another approach would be to use `position: fixed`, but we would have to make the content fixed-height. This would be difficult given the amount of text that is currently in the banner element:

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/fc99277c-3c68-49a4-8521-5a05369f0a29" />

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/d0965014-bd2d-4e13-8c53-726628e5cee8" />

<img width="516" alt="Image" src="https://github.com/user-attachments/assets/bd80bbfd-0b19-489a-9f5e-7bc81166f753" />

<img width="515" alt="Image" src="https://github.com/user-attachments/assets/8ae5aa0b-97b9-4219-bb1c-7d16613ec931" />

The [current JavaScript approach](https://github.com/django/djangoproject.com/blob/main/djangoproject/static/js/djangoproject.js#L154-L185) feels a bit complex to me and can lead to some odd scroll behavior.

---

I think this (S)CSS should work if we can make the element fixed-height:

```scss
html:has(#dev-warning, #outdated-warning) {
    scroll-padding-top: 38px;
}

body:has(#dev-warning, #outdated-warning) {
    margin-top: 38px;
}

#dev-warning,
#outdated-warning {
    height: 38px;
    position: fixed;
}
```

---

I'd be happy to implement a solution if there is a way forward here.
